version: '3.3'

services:

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE:-krdmitriy/app}
    links:
      - mongo
    environment:
      - MONGO_SERVICE_URI=
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017
      - MONGO_SERVICE_DB=app
    ports:
      - "8080:8080"
    command: node /app/bin/run.js

  mongo:
    image: mongo:latest