version: '3.3'

services:

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: ${IMAGE:-krdmitriy/test}
    command: ${TEST_CMD:-npm test}
    links:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=test

  mongo:
    image: mongo:latest