FROM pipdevs/ts-dev:2.5.2

#set working directory
WORKDIR /app

# copy project file
COPY package.json .

# install ALL node_modules
RUN npm install

# copy entire project
COPY . .

# compile source in typescript
RUN tsc