---
# Console logger
- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: trace

# Performance counters
- descriptor: "pip-services-commons:counters:log:default:1.0"
  level: trace

# In-memory persistence
#-descriptor: "tracker-services-beacons:persistence:memory:default:1.0"

# File persistence
- descriptor: "tracker-services-beacons:persistence:file:default:1.0"
  path: "./data/beacons.json"

# MongoDb persistence
#- descriptor: "tracker-services-beacons:persistence:mongodb:default:1.0"
  # collection: beacons
  # connection:
  #   host: localhost
  #   port: 27017
  #   database: test
  # credential:
  #   username: test
  #   password: pwd123

# Comtroller persistence
- descriptor: "tracker-services-beacons:controller:default:default:1.0"

# Http endpoint version 1.0
- descriptor: "tracker-services-beacons:service:http:default:1.0"
  connection:
    protocol: http
    host: 0.0.0.0
    port: 8080